// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuJr3s_eUde4gMElJxSV0cCUz0hm3TwFw',
    appId: '1:1000995314970:web:0cc208ff9b6be2566920a3',
    messagingSenderId: '1000995314970',
    projectId: 'smart-finance-app-dbdb9',
    authDomain: 'smart-finance-app-dbdb9.firebaseapp.com',
    storageBucket: 'smart-finance-app-dbdb9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRGN6lgfDLrDMTXAJr7cK5HUvS-xGAtvE',
    appId: '1:1000995314970:android:18b7b90dc9175ec46920a3',
    messagingSenderId: '1000995314970',
    projectId: 'smart-finance-app-dbdb9',
    storageBucket: 'smart-finance-app-dbdb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKiHGtca7WGqQQffdCPBYGIggQcGCo3oU',
    appId: '1:1000995314970:ios:5c3e54e6549921c16920a3',
    messagingSenderId: '1000995314970',
    projectId: 'smart-finance-app-dbdb9',
    storageBucket: 'smart-finance-app-dbdb9.firebasestorage.app',
    androidClientId:
        '1000995314970-67v2kt2k2am6nue9khs39b5qr1ne4ro2.apps.googleusercontent.com',
    iosClientId:
        '1000995314970-9hamh60i2isi2elqhtic8dadofho9pfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFinanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKiHGtca7WGqQQffdCPBYGIggQcGCo3oU',
    appId: '1:1000995314970:ios:5c3e54e6549921c16920a3',
    messagingSenderId: '1000995314970',
    projectId: 'smart-finance-app-dbdb9',
    storageBucket: 'smart-finance-app-dbdb9.firebasestorage.app',
    androidClientId:
        '1000995314970-67v2kt2k2am6nue9khs39b5qr1ne4ro2.apps.googleusercontent.com',
    iosClientId:
        '1000995314970-9hamh60i2isi2elqhtic8dadofho9pfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFinanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuJr3s_eUde4gMElJxSV0cCUz0hm3TwFw',
    appId: '1:1000995314970:web:a09e02144372f2fb6920a3',
    messagingSenderId: '1000995314970',
    projectId: 'smart-finance-app-dbdb9',
    authDomain: 'smart-finance-app-dbdb9.firebaseapp.com',
    storageBucket: 'smart-finance-app-dbdb9.firebasestorage.app',
  );
}
